name: OddArrow
main: com.isitbroken.oddarrow.OddArrow
version: 0.2.0
description: A Odd plugin for Bukkit.
commands:
commands:
  oa:
    description: Set OddArrow Mode!!
    usage: /oa <Rappad><Remote><Light><Replace><Create><Topsoil><Lightning><Off>, /oa <Replace><Create> <Material>
  boom:
    description: Make OddArrow Go Boom!!
    usage: /boom
  oar:
    description: Pemove OddArrow Player :-(
    usage: /oar